In [ ]:
!pip install pandas
import pandas as pd
import numpy as np

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
diccionarios = { 'curso1': [10,5,33,45,25,22],
                'curso2': [0,15,21,30,31,11],
                 'curso3': [15,5,1,10,42,21],
                 'curso4': [20,35,3,15,0,0]
                }

In [ ]:
pd.DataFrame(data=diccionarios)

   curso1  curso2  curso3  curso4
0      10       0      15      20
1       5      15       5      35
2      33      21       1       3
3      45      30      10      15
4      25      31      42       0
5      22      11      21       0

In [ ]:
matriz = np. arange(9).reshape(3,3)
matriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
pd.DataFrame(matriz)

In [ ]:
indice = ["enero","febrero","marzo","abril","mayo","junio"]

In [ ]:
cursos = pd.DataFrame(data=diccionarios,index=indice)
cursos

         curso1  curso2  curso3  curso4
enero        10       0      15      20
febrero       5      15       5      35
marzo        33      21       1       3
abril        45      30      10      15
mayo         25      31      42       0
junio        22      11      21       0

In [ ]:
pd.DataFrame(matriz, index = ["uno", "dos", "tres"], columns= ["a", "b", "c"])

      a  b  c
uno   0  1  2
dos   3  4  5
tres  6  7  8

In [ ]:
cursos["curso3"]

enero      15
febrero     5
marzo       1
abril      10
mayo       42
junio      21
Name: curso3, dtype: int64

In [ ]:
cursos[["curso3", "curso4"]]

         curso3  curso4
enero        15      20
febrero       5      35
marzo         1       3
abril        10      15
mayo         42       0
junio        21       0

In [ ]:
type(cursos["curso3"])

pandas.core.series.Series

In [ ]:
datos_np = np.arange(1,13).reshape(3,4) #Queda en un arreglo de 3 filas y 4 columnas

datos_np

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
datos = pd.DataFrame(datos_np)
datos

   0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [ ]:
datos[2] #Todos los datos del 2 a partir del indice

0     3
1     7
2    11
Name: 2, dtype: int64

In [ ]:
cursos[:1] #Los dos puntos me deja acceder a los valores numericos de las filas

       curso1  curso2  curso3  curso4
enero      10       0      15      20

In [ ]:
cursos[::2] #Va a tomar todos los datos de la fila pero de a dos pasos

       curso1  curso2  curso3  curso4
enero      10       0      15      20
marzo      33      21       1       3
mayo       25      31      42       0

In [ ]:
cursos["marzo":"mayo"] #se puede hacer indexacion a partir de los nombres (es por la utilizacion de los dos puntos)

       curso1  curso2  curso3  curso4
marzo      33      21       1       3
abril      45      30      10      15
mayo       25      31      42       0

In [ ]:
cursos["curso1"][2] #Me tiene que dar el valor de 33, ya que columna curso1 e indice marzo

/tmp/ipykernel_5426/1563643707.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  cursos["curso1"][2]

np.int64(33)

In [ ]:
cursos["curso1"]["marzo"] #Primero tiene que ir la columna

np.int64(33)

In [ ]:
cursos["curso2"][3:5] #Ir desde la fila 3 hasta la 4 (el 5 no se toma: recordar)

abril    30
mayo     31
Name: curso2, dtype: int64

In [ ]:
pd.Series([12,4,32,41,33,28], name= "py201")

0    12
1     4
2    32
3    41
4    33
5    28
Name: py201, dtype: int64

In [ ]:
inidce= ("enero", "febrero", "marzo", "abril", "mayo", "junio")

In [ ]:
serie = pd.Series([12,4,32,41,33,28], index=indice)
serie

enero      12
febrero     4
marzo      32
abril      41
mayo       33
junio      28
dtype: int64

In [ ]:
from datetime import datetime

In [ ]:
indice = ['gerente', 'supervisor', 'vendedor', 'cajero']
personal = pd.DataFrame({'nombres':('Juan Pérez',
                                    'María Sánchez',
                                    'Jorge Vargas',
                                    'Rodrigo Martínez'),
            'fechas':(datetime(1995,12,21),
                      datetime(1989,1,13),
                      datetime(1992,9,14),
                      datetime(1993,7,8)),
            'saldo': (2500,
                      5345,
                      np.nan,
                      11323.2),
            'al corriente':(True,
                            True,
                            False,
                            True)}, index=indice) #Los indices (filas) van a ser lo que esta en indice
indice
personal

                     nombres     fechas    saldo  al corriente
gerente           Juan Pérez 1995-12-21   2500.0          True
supervisor     María Sánchez 1989-01-13   5345.0          True
vendedor        Jorge Vargas 1992-09-14      NaN         False
cajero      Rodrigo Martínez 1993-07-08  11323.2          True

In [ ]:
personal.shape #Para saber la dimension

(4, 4)

In [ ]:
personal.index #Entrega los valores de los indices

Index(['gerente', 'supervisor', 'vendedor', 'cajero'], dtype='object')

In [ ]:
personal.columns #Entrega los valroes de las columnas

Index(['nombres', 'fechas', 'saldo', 'al corriente'], dtype='object')

In [ ]:
personal.reset_index() #Asignarle o cambiarle los valores o los nombres a los indices

        index           nombres     fechas    saldo  al corriente
0     gerente        Juan Pérez 1995-12-21   2500.0          True
1  supervisor     María Sánchez 1989-01-13   5345.0          True
2    vendedor      Jorge Vargas 1992-09-14      NaN         False
3      cajero  Rodrigo Martínez 1993-07-08  11323.2          True

In [ ]:
personal.set_index("nombres") #Coja los "nombres" o la variable que se mencione y convertirlos en indices

                     fechas    saldo  al corriente
nombres
Juan Pérez       1995-12-21   2500.0          True
María Sánchez    1989-01-13   5345.0          True
Jorge Vargas     1992-09-14      NaN         False
Rodrigo Martínez 1993-07-08  11323.2          True

In [ ]:
personal.info() #Da informcion

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, gerente to cajero
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   nombres       4 non-null      object
 1   fechas        4 non-null      datetime64[ns]
 2   saldo         3 non-null      float64
 3   al corriente  4 non-null      bool
dtypes: bool(1), datetime64[ns](1), float64(1), object(1)
memory usage: 304.0+ bytes

In [ ]:
datos = pd.DataFrame(np.arange(20).reshape(5,4),
                     columns = ("primero", "segundo", "tercero", "cuarto"))
datos

   primero  segundo  tercero  cuarto
0        0        1        2       3
1        4        5        6       7
2        8        9       10      11
3       12       13       14      15
4       16       17       18      19

In [ ]:
datos.iloc[2,[3]]

cuarto    11
Name: 2, dtype: int64

In [ ]:
datos.iloc[2,3]

np.int64(11)

In [ ]:
type(datos.iloc[2,[3]])

pandas.core.series.Series

In [ ]:
datos.iloc[2,[2,1,3]]

tercero    10
segundo     9
cuarto     11
Name: 2, dtype: int64

In [ ]:
datos.iloc[2,[0,1,2,2]]

primero     8
segundo     9
tercero    10
tercero    10
Name: 2, dtype: int64

In [ ]:
datos.iloc[2]

primero     8
segundo     9
tercero    10
cuarto     11
Name: 2, dtype: int64

In [ ]:
personal.loc["supervisor", ["fechas"]]

fechas    1989-01-13 00:00:00
Name: supervisor, dtype: object

In [ ]:
personal.loc["supervisor", "fechas"]

Timestamp('1989-01-13 00:00:00')

In [ ]:
personal["saldo"] > 3000

gerente       False
supervisor     True
vendedor      False
cajero         True
Name: saldo, dtype: bool

In [ ]:
personal.loc[personal["saldo"] > 3000]

                     nombres     fechas    saldo  al corriente
supervisor     María Sánchez 1989-01-13   5345.0          True
cajero      Rodrigo Martínez 1993-07-08  11323.2          True

In [ ]:
personal.loc[personal["al corriente"]] #solo me arrojara los verdaderos

                     nombres     fechas    saldo  al corriente
gerente           Juan Pérez 1995-12-21   2500.0          True
supervisor     María Sánchez 1989-01-13   5345.0          True
cajero      Rodrigo Martínez 1993-07-08  11323.2          True

In [ ]:
personal.loc[personal["al corriente"] == False]

               nombres     fechas  saldo  al corriente
vendedor  Jorge Vargas 1992-09-14    NaN         False

In [ ]:
indice_1 = ("lunes", "martes", "miércoles")
marco_1 = pd.DataFrame({'Centro':[1520,1640,1043],
                       'Sur':[1422,1673,1534],
                      'Oriente':[1021,1073,1100]},
                       index=indice_1)
indice_1
marco_1

           Centro   Sur  Oriente
lunes        1520  1422     1021
martes       1640  1673     1073
miércoles    1043  1534     1100

In [ ]:
indice_2 = ("jueves", "viernes", "sábado")
marco_2 = pd.DataFrame({'Centro':[1321,1459,1875],
                       'Sur':[1622,1841,1920],
                      'Oriente':[1500,1432,1491]},
                      index=indice_2)

indice_2
marco_2

         Centro   Sur  Oriente
jueves     1321  1622     1500
viernes    1459  1841     1432
sábado     1875  1920     1491

In [ ]:
pd.concat([marco_1, marco_2]) #Union

           Centro   Sur  Oriente
lunes        1520  1422     1021
martes       1640  1673     1073
miércoles    1043  1534     1100
jueves       1321  1622     1500
viernes      1459  1841     1432
sábado       1875  1920     1491

In [ ]:
pd.concat([marco_1, marco_2], axis = 1)

           Centro     Sur  Oriente  Centro     Sur  Oriente
lunes      1520.0  1422.0   1021.0     NaN     NaN      NaN
martes     1640.0  1673.0   1073.0     NaN     NaN      NaN
miércoles  1043.0  1534.0   1100.0     NaN     NaN      NaN
jueves        NaN     NaN      NaN  1321.0  1622.0   1500.0
viernes       NaN     NaN      NaN  1459.0  1841.0   1432.0
sábado        NaN     NaN      NaN  1875.0  1920.0   1491.0

In [ ]:
pd.concat([marco_1, marco_2], axis = 1)["Centro"]

           Centro  Centro
lunes      1520.0     NaN
martes     1640.0     NaN
miércoles  1043.0     NaN
jueves        NaN  1321.0
viernes       NaN  1459.0
sábado        NaN  1875.0